# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/node:18.20.5
    branches:
      only:
        - main
        - develop
        - feature/*
        - dev
    steps:
      - run: echo "hello circleci"
      - run: npm -v
      - run: node -v
      - add_ssh_keys:
          fingerprints:
            - "SHA256:S1ruwwzCgstYdVw9TgOp+b9He7hiYnsvOivnJbonlPk"
      - checkout
      - run
        name: Install dependencies
        command: npm install\
      - run
        name: Build
        command: npm run build
