version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.20.5
    steps:
      - checkout
      - run: echo "hello circleci"
      - run: npm -v
      - run: node -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
